version: "3.9"

volumes:
  db-store:
  pma-session-store:

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    command: go run cmd/main.go

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  pma:
    build:
      context: .
      dockerfile: ./docker/pma/Dockerfile
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - target: 80
        published: 8088
        protocol: tcp
        mode: host
    volumes:
      - pma-session-store:/sessions