CREATE TABLE tasks (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    deadline DATETIME NOT NULL,
    is_favorite SMALLINT NOT NULL DEFAULT(0),
    is_completed SMALLINT NOT NULL DEFAULT(0),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
