@startuml
left to right direction

hide circle
hide method

package タスクリスト {
    class タスク {
        タスク名
        期限
        お気に入りされているかどうか
        完了したかどうか
    }

    note right: タイトルは1〜30文字

    class 提案タスク {
    }

    enum 並び替えの種類 {
        タスク名
        期限
        お気に入り
    }

    enum 並び替えの順序 {
        昇順
        降順
    }

    タスク -o 提案タスク
}
@enduml
