@startuml
left to right direction

hide circle
hide method

package タスクリスト {
    class タスク一覧 {
        並び替え(SortType, OrderType)
    }

    class タスク {
        タスク名
        期限
        お気に入りされているかどうか
        完了したかどうか
    }

    note right: タイトルは1〜30文字

    enum 並び替えの種類 {
        タスク名
        期限
        お気に入り
    }

    enum 並び替えの順序 {
        昇順
        降順
    }

    タスク -* タスク一覧
}
@enduml
