@startuml
left to right direction

hide circle
hide method

package タスクリスト {
    class タスク一覧 {
    }

    class タスク {
        タスク名
        期限
        お気に入り
        完了したかどうか
    }
    note right: ・タイトルは1〜30文字

    タスク - タスク一覧
}
@enduml