@startuml
left to right direction

rectangle "TODOリスト" {
  ユーザー --> (タスクを追加する/編集する/削除する)
  ユーザー --> (タスクを完了済み/未完了にする)
  ユーザー --> (期限日を設定する/変更する)
  ユーザー --> (ラベルを追加する/編集する/削除する)
  ユーザー --> (カテゴリを追加する/編集する/削除する)
  ユーザー --> (タスクをフィルタリングする)
  ユーザー --> (タスクを並び替える)
}

@enduml